-- DML for transactions

-- Store a transaction when it has completed
INSERT INTO trades VALUES (trade id generated by python, username, trade time in UTC, coin name, coin amount, usd amount);

-- Retrive transacctions in a specific timeframe
SELECT * FROM trades WHERE TRADE_TIME between 'python variable with start date and time in form YYYY-MM-DD hh:mm:ss' AND 'python variable with end date and time YYYY-MM-DD hh:mm:ss';

-- Retrieve transactions in a certain crypto ccurrency 
SELECT * FROM trades WHERE COIN_NAME = 'python variable with coin name';
